on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          formatted_note="こんにちは"
          echo "release_note=$formatted_note" >> $GITHUB_ENV
      - run: echo ${{ env.release_note }}
