name: Run
on:
  workflow_dispatch:
  
permissions:
  actions: write
  id-token: write
  contents: read
  packages: write

jobs:
  should_skip_tests:
    name: Check if tests can be skipped
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: 'same_content_newer'
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["workflow_dispatch"]'
