on:
  workflow_dispatch:

jobs:
  job-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew update
      
  job-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: brew update
