on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "content for this file" > myfile.txt
      - uses: actions/cache@v4
        with:
          path: myfile.txt
          key: https://github.com/anthmmatic/public-testbox.git
      - run: cat myfile.txt
