on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
