on:
  workflow_dispatch:

jobs:
  job1:
    concurrency:
      group: ${{ github.ref != 'refs/heads/main' && '(github.workflow)-(github.ref)' || null }}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30

  job2:
    concurrency:
      group: ${{ github.ref != 'refs/heads/main' && '(github.workflow)-(github.ref)' || null }}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
