on:
  workflow_dispatch:

jobs:
  job1:
    concurrency: ${{ github.ref != 'refs/heads/main' }} && ${{ github.workflow }}-${{ github.ref }} || ''
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30

  job2:
    concurrency: ${{ github.ref != 'refs/heads/main' }} && ${{ github.workflow }}-${{ github.ref }} || ''
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
