on:
  workflow_dispatch:

jobs:
  job1:
    concurrency: ${{ github.ref != 'refs/heads/main' && github.run_id || 'job1' }}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30

  job2:
    concurrency: ${{ github.ref != 'refs/heads/main' && github.run_id || 'job2' }}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
