on:
  workflow_dispatch:
  workflow_call:

jobs:
  init:
    strategy:
      matrix:
        id: [0,1,2,3,4]
    uses: ./.github/workflows/reusewf.yml
    with:
      id: ${{ matrix.id }}
  dep:
    needs: init
    if: (!cancelled() && !failure())
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
