on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
  dep:
    needs: init
    if: (!cancelled() && !failure())
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
