on:
  workflow_dispatch:
  workflow_call:

jobs:
  init:
    strategy:
      matrix:
        id: [0,1,2,3,4,5,6]
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ matrix.id }} -eq 1 ]]; then
            exit 1
          fi
          sleep 60
  dep:
    needs: init
    if: (!cancelled() && !failure() && inputs.deployment_type != 'none')
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
