on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  dep:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
  dep2:
    needs: dep
    if: (!cancelled() && !failure())
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
