on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        continue-on-error: true
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-primes
      - run: echo "done"

  job-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start"
      - continue-on-error: true
        timeout-minutes: 1
        run: |
          echo "sleep"
          sleep 2m
      - run: echo "done"
