on:
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
           curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ github.token }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/releases \
           -d '{"tag_name":"v2.0.21","target_commitish":"55aa4b03684b681bb6337b8d4a3c3b981044ed54","name":"test release actions","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
