on: create

jobs:
  main:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.ref_type }}
      - run: echo ${{ github.event.ref }}
