on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      jbjson: ${{ steps.setter.outputs.json }}
    steps:
      - uses: actions/checkout@v4
      - id: setter
        run: |
          event_name=${{github.event_name}}
          jobs=$(cat test.json)
          echo "jobs=$jobs[$event_name]" >> "$GITHUB_OUTPUT"
