on:
  workflow_call:
    inputs:
      jbvals:
        description: 'job list'
        required: true
        type: string

env:
  JBVALSE: ${{ inputs.jbvals[github.event_name] }}

jobs:
  primer-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.job }}"

  primer-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.job }}"

  job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.job }}"

  job-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.job }}"

  dynamic:
    needs: ${{ fromJSON(env.JBVALSE) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.jbvals }}"
