on:
  workflow_dispatch:

jobs:
  create-new:
    runs-on: ubuntu-latest
    environment: never-have-i-ever2
    concurrency: main
    permissions:
      deployments: write
    steps:
      - run: echo 'done'
