on:
  workflow_dispatch:

jobs:
  deploy-multi:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        prefix: ["0", "1", "2", "3", "4", "5"]
    steps:
      - run: echo "done"
