on:
  workflow_dispatch:

concurrency: main

jobs:
  deploy-multi-1:
    runs-on: ubuntu-latest
    environment:
      name: Production
    strategy:
      matrix:
        prefix: ["0", "1", "2", "3", "4", "5", "6", "7", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - run: echo "done"

  deploy-multi-2:
    runs-on: ubuntu-latest
    environment:
      name: Production
    strategy:
      matrix:
        prefixa: ["0", "1", "2", "3", "4", "5", "6", "7", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - run: echo "done"
