name: Team Review Requested -> Request Members

on:
  pull_request:
    types:
      - review_requested
      
jobs:
  expand_teams:
    name: Expand teams
    runs-on: ubuntu-latest
    #if: github.event.requested_team 
    strategy:
      matrix:
        team: [
          {
            name: 'just-members',
            members: [
              'Amso64',
              'stand-in-anth'
            ],
          },
          {
            name: 'sia',
            members: [
              'stand-in-anth'
            ],
          },
        ]
    steps:
      - name: Add team members
        id: add_members
        if: github.event.requested_team.slug == matrix.team.name
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/pulls/{pull_number}/requested_reviewers
          repo: ${{ github.repository }}
          pull_number: ${{ github.event.number }}
          reviewers: ${{ matrix.team.members }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
