on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if (github.run_attempt == '1')
          then
            exit 1
          else
            exit 0
          fi
