on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dependabot/alerts
      
