on:
  workflow_dispatch:

jobs:
  generate-logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lone"
      - name: Group of log lines
        run: |
            echo "start"
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
