on:
  workflow_dispatch:

jobs:
  generate-logs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in {1..4000}
          do
             echo "[32mLog line: $i [0m"
          done
