on:
  workflow_dispatch:

jobs:
  generate-logs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in {1..1000000}
          do
             echo -e "\033[31mLogline:$i\033[0m"
             echo -e "\033[32mLogline:$i\033[0m"
             echo -e "\033[33mLogline:$i\033[0m"
          done
