on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          echo "GH_VERSION=$(gh version | tr -d '\n')" >> $GITHUB_ENV
      - run: echo $GH_VERSION
