on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "first"
      - run: exit 1
      - if: false
        run: echo "skip"
      - if: always()
        run: echo "ran anyway"
