on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TFO=$(terraform output -raw lb_address | tr -d '\n')" >> $GITHUB_ENV
        env:
          TF_LOG: TRACE
      - run: echo $TFO
