on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        ids: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - run: sleep 30
        shell: bash
