on:
  delete:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.ref }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
