on:
  workflow_dispatch:

jobs:
  onsuccess:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      - run: echo $MYSECRET
        env:
          MYSECRET: ${{ secrets.VALUE }}

  onfailure:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - if: failure()
        run: echo $MYSECRET
        env:
          MYSECRET: ${{ secrets.VALUE }}
