on:
  release:
    types: [created]
  
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.release.tag_name }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
