on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - run: $PSVersionTable.PSVersion
    
    - name: Setup PowerShell
      run: |
        # Update the PowerShellGet module
        Install-Module -Name PowerShellGet -Force -AllowClobber

        # Install latest PowerShell
        iex "& { $(irm https://aka.ms/install-powershell.ps1) }"
        
    - name: Verify PowerShell Version
      run: $PSVersionTable.PSVersion
