on:
  workflow_dispatch:

jobs:
  python-tagged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11
          cache: pip

  python-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5 # v5.6.0
        with:
          python-version: 3.11
          cache: pip
