on:
  workflow_dispatch:
  workflow_call:
    inputs:
      id:
        required: true
        type: string

jobs:
  job-name:
    name: First-text
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
