on:
  workflow_dispatch:
  workflow_call:
    inputs:
      id:
        required: false
        type: string

jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
  second-run:
    if: false
    needs: [first-run]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
  first-skip:
    needs: [first-run, second-run]
    if: false
    concurrency: first
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
  second-skip:
    needs: [first-run, second-run]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
  third-skip:
    needs: [first-run, second-run]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
