on:
  workflow_dispatch:
  workflow_call:
    inputs:
      id:
        required: true
        type: string
      id2:
        type: string

jobs:
  job-name:
    environment: ${{ inputs.id }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.DEV_ENV }}"
