on:
  workflow_dispatch:
  workflow_call:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthmmatic/public-testbox/.github/actions/my-act@main
