on:
  workflow_dispatch:
  workflow_call:
    inputs:
      id:
        required: false
        type: string

jobs:
  first-run:
    uses: ./.github/workflows/reuse-nested.yml
  second-run:
    if: false
    uses: ./.github/workflows/reuse-nested.yml
  first-skip:
    if: false
    uses: ./.github/workflows/reuse-nested.yml
  second-skip:
    if: false
    uses: ./.github/workflows/reuse-nested.yml
  third-skip:
    if: false
    uses: ./.github/workflows/reuse-nested.yml
