on:
  workflow_dispatch:
  workflow_call:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          value=("${{ secrets.AV_SEC }}")
          echo "$value"
          if [[ -z "$value" ]]
          then
            exit 1;
          fi
            
