on:
  workflow_dispatch:
  workflow_call:
    inputs:
      id:
        required: true
        type: string

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ inputs.id }} -eq 1 ]]; then
            exit 1
          fi
          sleep 60
