on:
  workflow_call:
    inputs:
      port_payload:
        required: false
        description: "Port's payload"
        type: string

jobs:
  job-name:
    runs-on: ubuntu-latest
    if: fromJSON(inputs.port_payload).fork == 'false'
    steps:
      - run: echo "Done"
