on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ${{ github.ref_name }}
        required: false
        description: version to tag with the Docker image

jobs:
  job-name:
    concurrency:
      group: main-reuse-1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
