on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-name-reuse:
    strategy:
      matrix:
        id: [0,1,2,3,4,5,6,7,8,9]
    uses: anthmmatic/public-testbox/.github/workflows/reusewf.yml@main
    secrets: inherit
