on:
  workflow_call:
    inputs:
      port_payload:
        required: false
        description: "Port's payload"
        default: "{}"
        type: string

jobs:
  job-name:
    runs-on: ubuntu-latest
    if: fromJSON(inputs.port_payload).fork == false
    steps:
      - run: echo "Done"

  job-other:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.port_payload }}"
      - run: echo "${{ fromJSON(inputs.port_payload).fork }}"
