on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-main:
    runs-on: ubuntu-latest
    if: ${{ vars.FOOR == '' }}
    steps:
      - run: echo "${{ vars.FOOR == '' }}"
      - run: echo "${{ vars.FOOR }}"
