on:
  workflow_dispatch:

jobs:
  job-main:
    runs-on: ubuntu-latest
    environment:
      name: testing
    if: ${{ vars.FOO == '' }}
    steps:
      - run: echo "${{ vars.FOO == '' }}"
      - run: echo "${{ vars.FOO }}"
