on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-main:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - if: ${{ vars.FOO == 'MAINVAL' }}
        run: echo "${{ vars.FOO }}"
      - if: ${{ vars.FOO == 'FEATVAL' }}
        run: echo "${{ vars.FOO }}"
