on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: |
          curl -s -i \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables/MY_VAR" \
            -d '{"name":"MY_VAR","value":"NEWVAL"}'
