on:
  workflow_dispatch:

jobs:
  to-run:
    runs-on: ubuntu-latest
    concurrency:
      group: group-one
      cancel-in-progress: true
    steps:
      - run: |
          for i in {0..59}
          do
             echo "loop $i";
             sleep 1;
          done

  to-wait:
    runs-on: ubuntu-latest
    environment: waiter-1
    concurrency:
      group: group-one
      cancel-in-progress: true
    steps:
      - run: echo "Done."
