on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: windows-latest
    steps:
      - run: cat "C:\Program Files\Git\etc\gitconfig"
      - run: git config --global core.fsmonitor false
      - run: cat "C:\Program Files\Git\etc\gitconfig"
