on:
  workflow_dispatch:

jobs:
  win-22:
    runs-on: windows-latest
    steps:
      - run: git --version
        shell: bash
  win-25:
    runs-on: windows-2025
    steps:
      - run: git --version
        shell: bash
