on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: windows-latest
    steps:
      - run: |
          git config --global core.fsmonitor true
          cat "C:\Program Files\Git\etc\gitconfig"
          git config --global core.fsmonitor false
          cat "C:\Program Files\Git\etc\gitconfig"
